CREATE TABLE "device_tokens" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "device_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"device_id" text NOT NULL,
	"platform" text DEFAULT 'ios' NOT NULL,
	"push_token" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"preferences" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"app_version" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "device_tokens_platform_check" CHECK ("device_tokens"."platform" in ('ios','web'))
);
--> statement-breakpoint
CREATE TABLE "notification_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"trip_client_id" text NOT NULL,
	"day_iso" date NOT NULL,
	"kind" text NOT NULL,
	"dedupe_key" text NOT NULL,
	"state_version" text,
	"opened_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "suggestion_feedback" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "suggestion_feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"trip_client_id" text NOT NULL,
	"day_iso" date NOT NULL,
	"suggestion_key" text NOT NULL,
	"action" text NOT NULL,
	"source" text DEFAULT 'unknown' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "suggestion_feedback_action_check" CHECK ("suggestion_feedback"."action" in ('ACCEPTED','SKIPPED','DISMISSED','REPLACED'))
);
--> statement-breakpoint
CREATE TABLE "trip_memories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"trip_client_id" text NOT NULL,
	"day_index" integer,
	"activity_id" text,
	"type" text NOT NULL,
	"caption" text,
	"asset_refs" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"lat" double precision,
	"lng" double precision,
	"at_minutes" integer,
	"captured_at" timestamp with time zone DEFAULT now() NOT NULL,
	"client_key" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trip_memories_type_check" CHECK ("trip_memories"."type" in ('PHOTO','NOTE','VISIT','MOMENT'))
);
--> statement-breakpoint
ALTER TABLE "device_tokens" ADD CONSTRAINT "device_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_log" ADD CONSTRAINT "notification_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suggestion_feedback" ADD CONSTRAINT "suggestion_feedback_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_memories" ADD CONSTRAINT "trip_memories_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "device_tokens_user_device_uidx" ON "device_tokens" USING btree ("user_id","device_id");--> statement-breakpoint
CREATE INDEX "device_tokens_user_idx" ON "device_tokens" USING btree ("user_id","enabled");--> statement-breakpoint
CREATE UNIQUE INDEX "notification_log_user_key_uidx" ON "notification_log" USING btree ("user_id","dedupe_key");--> statement-breakpoint
CREATE INDEX "notification_log_lookup_idx" ON "notification_log" USING btree ("user_id","trip_client_id","day_iso");--> statement-breakpoint
CREATE UNIQUE INDEX "suggestion_feedback_key_uidx" ON "suggestion_feedback" USING btree ("user_id","trip_client_id","day_iso","suggestion_key");--> statement-breakpoint
CREATE INDEX "suggestion_feedback_lookup_idx" ON "suggestion_feedback" USING btree ("user_id","trip_client_id","day_iso");--> statement-breakpoint
CREATE UNIQUE INDEX "trip_memories_user_key_uidx" ON "trip_memories" USING btree ("user_id","client_key");--> statement-breakpoint
CREATE INDEX "trip_memories_trip_idx" ON "trip_memories" USING btree ("user_id","trip_client_id","day_index");