CREATE TABLE "candidate_reactions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "candidate_reactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"candidate_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"reaction" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "candidate_reactions_reaction_check" CHECK ("candidate_reactions"."reaction" in ('MUST','OK','PASS'))
);
--> statement-breakpoint
CREATE TABLE "trip_activity" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"trip_id" uuid NOT NULL,
	"actor_id" uuid,
	"kind" text NOT NULL,
	"subject" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trip_activity_kind_check" CHECK ("trip_activity"."kind" in ('MEMBER_JOINED','MEMBER_LEFT','MEMBER_REMOVED','CANDIDATE_PROPOSED','CANDIDATE_SCHEDULED','CANDIDATE_REJECTED','REACTION','COMMENT_ADDED','SCHEDULE_CHANGED','BOOKING_ADDED'))
);
--> statement-breakpoint
CREATE TABLE "trip_candidates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_candidates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"trip_id" uuid NOT NULL,
	"title" text NOT NULL,
	"place_id" text,
	"lat" double precision,
	"lng" double precision,
	"addr" text,
	"note" text,
	"url" text,
	"proposed_by" uuid NOT NULL,
	"status" text DEFAULT 'PROPOSED' NOT NULL,
	"scheduled_ref" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trip_candidates_title_check" CHECK (btrim("trip_candidates"."title") <> ''),
	CONSTRAINT "trip_candidates_status_check" CHECK ("trip_candidates"."status" in ('PROPOSED','ACCEPTED','REJECTED','SCHEDULED'))
);
--> statement-breakpoint
CREATE TABLE "trip_comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"trip_id" uuid NOT NULL,
	"candidate_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"body" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trip_comments_body_check" CHECK (btrim("trip_comments"."body") <> '' and length("trip_comments"."body") <= 500)
);
--> statement-breakpoint
CREATE TABLE "trip_invites" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_invites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"trip_id" uuid NOT NULL,
	"token_hash" text NOT NULL,
	"role" text NOT NULL,
	"created_by" uuid NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"max_uses" integer,
	"use_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trip_invites_token_hash_unique" UNIQUE("token_hash"),
	CONSTRAINT "trip_invites_role_check" CHECK ("trip_invites"."role" in ('EDITOR','VIEWER')),
	CONSTRAINT "trip_invites_max_uses_check" CHECK ("trip_invites"."max_uses" is null or "trip_invites"."max_uses" > 0)
);
--> statement-breakpoint
ALTER TABLE "candidate_reactions" ADD CONSTRAINT "candidate_reactions_candidate_id_trip_candidates_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "public"."trip_candidates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "candidate_reactions" ADD CONSTRAINT "candidate_reactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_activity" ADD CONSTRAINT "trip_activity_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_activity" ADD CONSTRAINT "trip_activity_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_candidates" ADD CONSTRAINT "trip_candidates_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_candidates" ADD CONSTRAINT "trip_candidates_proposed_by_users_id_fk" FOREIGN KEY ("proposed_by") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_comments" ADD CONSTRAINT "trip_comments_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_comments" ADD CONSTRAINT "trip_comments_candidate_id_trip_candidates_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "public"."trip_candidates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_comments" ADD CONSTRAINT "trip_comments_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_invites" ADD CONSTRAINT "trip_invites_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_invites" ADD CONSTRAINT "trip_invites_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "candidate_reactions_cand_user_uidx" ON "candidate_reactions" USING btree ("candidate_id","user_id");--> statement-breakpoint
CREATE INDEX "trip_activity_trip_idx" ON "trip_activity" USING btree ("trip_id","id");--> statement-breakpoint
CREATE INDEX "trip_candidates_trip_idx" ON "trip_candidates" USING btree ("trip_id","created_at");--> statement-breakpoint
CREATE INDEX "trip_comments_cand_idx" ON "trip_comments" USING btree ("candidate_id","created_at");--> statement-breakpoint
CREATE INDEX "trip_invites_trip_idx" ON "trip_invites" USING btree ("trip_id","created_at");