CREATE TABLE "trip_snapshots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"client_id" text NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"data" jsonb NOT NULL,
	"source_revision" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trip_snapshots_revision_check" CHECK ("trip_snapshots"."source_revision" is null or "trip_snapshots"."source_revision" > 0)
);
--> statement-breakpoint
ALTER TABLE "trip_snapshots" ADD CONSTRAINT "trip_snapshots_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "trip_snapshots_user_client_created_idx" ON "trip_snapshots" USING btree ("user_id","client_id","created_at");