CREATE TABLE "ops_backup_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ops_backup_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ok" boolean NOT NULL,
	"bytes" bigint,
	"destination" text NOT NULL,
	"note" text
);
--> statement-breakpoint
CREATE INDEX "ops_backup_runs_finished_idx" ON "ops_backup_runs" USING btree ("finished_at");