-- Push 전달 기반 — 기기 토큰과 발송 기록.
--
-- 알림을 '많이 보내는 것'이 목표가 아니라서, 이 두 테이블의 실제 역할은 **보내지 않기 위한 것**이다:
-- notification_log의 dedupe_key가 이미 있으면 같은 상황을 다시 알리지 않는다.
--
-- 위치는 저장하지 않는다. 출발 판단은 기기가 하고, 서버는 그 결과의 발송 여부만 기록한다.
begin;

create table if not exists public.device_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  device_id text not null,                       -- 기기별 고유값 (앱이 만들어 Keychain에 보관)
  platform text not null default 'ios' check (platform in ('ios', 'web')),
  push_token text not null,
  enabled boolean not null default true,
  -- 사용자가 끌 수 있는 범주(§41). 없는 키는 켜진 것으로 본다.
  preferences jsonb not null default '{}'::jsonb,
  app_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, device_id)
);

-- 같은 토큰이 다른 사용자에게 재발급될 수 있다(기기 양도·재설치) → 토큰 기준으로도 찾을 수 있어야 한다.
create index if not exists device_tokens_token_idx on public.device_tokens(push_token);
create index if not exists device_tokens_user_idx on public.device_tokens(user_id, enabled);

create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  trip_client_id text not null,
  day_iso date not null,
  kind text not null,
  -- adaptive.notificationPlan이 만든 키: trip|day|kind|source|stage.
  -- 단계가 바뀌면 키가 달라져 '정말 새로운 상황'만 통과한다.
  dedupe_key text not null,
  -- 그때의 상태 지문 — 낡은 알림으로 낡은 제안을 적용하지 않기 위해(§47)
  state_version text,
  opened_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, dedupe_key)
);

create index if not exists notification_log_lookup_idx
  on public.notification_log(user_id, trip_client_id, day_iso);

alter table public.device_tokens enable row level security;
alter table public.notification_log enable row level security;

do $$ declare p record; begin
  for p in select policyname, tablename from pg_policies
           where schemaname='public' and tablename in ('device_tokens','notification_log') loop
    execute format('drop policy %I on public.%I', p.policyname, p.tablename);
  end loop;
end $$;

create policy "device_tokens_owner_select" on public.device_tokens
  for select to authenticated using ((select auth.uid())=user_id);
create policy "device_tokens_owner_insert" on public.device_tokens
  for insert to authenticated with check ((select auth.uid())=user_id);
create policy "device_tokens_owner_update" on public.device_tokens
  for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "device_tokens_owner_delete" on public.device_tokens
  for delete to authenticated using ((select auth.uid())=user_id);

create policy "notification_log_owner_select" on public.notification_log
  for select to authenticated using ((select auth.uid())=user_id);
create policy "notification_log_owner_insert" on public.notification_log
  for insert to authenticated with check ((select auth.uid())=user_id);
create policy "notification_log_owner_update" on public.notification_log
  for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "notification_log_owner_delete" on public.notification_log
  for delete to authenticated using ((select auth.uid())=user_id);

revoke all on public.device_tokens, public.notification_log from anon;
grant select, insert, update, delete on public.device_tokens, public.notification_log to authenticated;

commit;
