-- 함께하기(Collaborative Trip Planning) 1단계 — 멤버십 · 권한 · 초대.
--
-- 여행은 여전히 trips 한 행(문서 jsonb)이다. 여기서 바꾸는 것은 **누가 그 행을 볼 수 있고 바꿀 수 있는가**다.
--   trips.user_id  = 소유자(OWNER). 바뀌지 않는다(트리거로 잠근다 — 소유권 이전은 다음 단계).
--   trip_members   = 소유자 + 초대로 들어온 EDITOR/VIEWER. 소유자 행은 자동으로 생기고(트리거·백필) 지워지지 않는다.
--   trip_invites   = 초대 링크. **토큰 원문은 저장하지 않는다**(sha256만) — DB가 새어도 링크를 재구성할 수 없다.
--
-- 접근은 DB가 결정한다(§65~67). 클라이언트가 버튼을 감추는 것은 편의일 뿐이다:
--   읽기 : 소유자 OR 활성 멤버
--   쓰기 : 소유자 OR EDITOR  (VIEWER의 sync_trip은 42501로 거절된다)
--   삭제 : 소유자만          (멤버는 leave_trip으로 나간다)
--   초대 : 소유자만 만들고 취소한다. 수락은 토큰을 가진 로그인 사용자 — **수락 전에는 여행 본문을 볼 수 없다.**
--
-- trips 정책이 trip_members를 보고 trip_members 정책이 trips를 보면 재귀가 된다. 그래서 tc_trip_role()을
-- security definer(RLS 우회)로 두고 양쪽 정책이 그 함수만 부른다 — Supabase가 문서화한 방식이다.
--
-- ⚠️ client_id(여행 문서의 id)는 **사용자별로만** 유일하다. 같은 client_id를 내가 소유한 것과 남이 공유한 것이
-- 동시에 있을 수 있어(확률은 낮다) 모든 조회는 소유한 것을 우선한다.
--
-- ⚠️ trips.id의 타입을 가정하지 않는다. 저장소의 기본 마이그레이션은 bigint identity로 만들지만 **운영 DB는 그보다
-- 먼저 만들어져 uuid다**(create table if not exists라 그대로 남았다). 그래서 trip_id 컬럼과 함수 인자는 전부
-- public.trips.id의 실제 타입(%type · format_type)을 따라간다 — 어느 쪽에 적용해도 같은 결과가 된다.
begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- ── 테이블 ──────────────────────────────────────────────────────────────────
-- trip_id는 trips.id와 같은 타입이어야 외래키가 잡힌다 — 실제 타입을 읽어 만든다.

do $$ declare t text; begin
  select format_type(a.atttypid, a.atttypmod) into t
    from pg_attribute a where a.attrelid='public.trips'::regclass and a.attname='id';
  execute format($sql$
    create table if not exists public.trip_members (
      id bigint generated by default as identity primary key,
      trip_id %s not null references public.trips(id) on delete cascade,
      user_id uuid not null references auth.users(id) on delete cascade,
      role text not null check (role in ('OWNER','EDITOR','VIEWER')),
      status text not null default 'ACTIVE' check (status in ('INVITED','ACTIVE','LEFT','REMOVED')),
      -- 이 여행에서 보일 이름. 계정 정보(이메일 등)는 여행에 노출하지 않는다(§69). 여행마다 다르게 둘 수 있다.
      display_name text,
      invited_by uuid references auth.users(id) on delete set null,
      joined_at timestamptz,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      unique (trip_id, user_id)
    )$sql$, t);
  execute format($sql$
    create table if not exists public.trip_invites (
      id bigint generated by default as identity primary key,
      trip_id %s not null references public.trips(id) on delete cascade,
      -- sha256(token) hex. 토큰 원문은 만든 순간 한 번만 돌려주고 어디에도 남기지 않는다.
      token_hash text not null unique,
      role text not null check (role in ('EDITOR','VIEWER')),
      created_by uuid not null references auth.users(id) on delete cascade,
      expires_at timestamptz not null,
      revoked_at timestamptz,
      max_uses int check (max_uses is null or max_uses > 0),
      use_count int not null default 0,
      created_at timestamptz not null default now()
    )$sql$, t);
end $$;
create index if not exists trip_members_user_idx on public.trip_members(user_id, status);
create index if not exists trip_invites_trip_idx on public.trip_invites(trip_id, created_at desc);

-- ── 헬퍼 (정책 안에서 불린다 — security definer라 RLS 재귀가 없다) ────────────

-- 호출자의 이 여행에 대한 역할. 소유자면 OWNER, 활성 멤버면 그 역할, 아니면 null.
-- 인자 타입은 trips.id를 그대로 따른다(%type) — 운영은 uuid, 새 설치는 bigint.
create or replace function public.tc_trip_role(p_trip_id public.trips.id%type)
returns text language sql stable security definer set search_path=public as $$
  select case
    when exists(select 1 from public.trips t where t.id=p_trip_id and t.user_id=auth.uid()) then 'OWNER'
    else (select m.role from public.trip_members m
           where m.trip_id=p_trip_id and m.user_id=auth.uid() and m.status='ACTIVE' limit 1)
  end
$$;

-- 이 client_id의 여행에서 나갔거나 내보내진 적이 있는가. 나간 사람의 로컬 사본이 sync_trip의
-- "없으면 새로 만든다" 분기를 타고 **조용히 제 계정으로 복제되는 것**을 막는다.
create or replace function public.tc_was_member(p_client_id text)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.trips t join public.trip_members m on m.trip_id=t.id
     where t.client_id=p_client_id and m.user_id=auth.uid() and m.status in ('LEFT','REMOVED')
  )
$$;

-- 시그니처가 trips.id 타입을 따르므로 권한도 실제 타입으로 건다.
do $$ declare t text; begin
  select format_type(a.atttypid, a.atttypmod) into t
    from pg_attribute a where a.attrelid='public.trips'::regclass and a.attname='id';
  execute format('revoke all on function public.tc_trip_role(%s) from public, anon', t);
  execute format('grant execute on function public.tc_trip_role(%s) to authenticated', t);
end $$;
revoke all on function public.tc_was_member(text) from public, anon;
grant execute on function public.tc_was_member(text) to authenticated;

-- ── 트리거 ──────────────────────────────────────────────────────────────────

-- 소유자는 바뀌지 않는다. EDITOR가 PostgREST로 user_id를 제 것으로 바꾸면 update 정책의 with check가
-- (새 행 기준으로) 통과해 버린다 — 정책만으로는 막을 수 없어 트리거로 잠근다.
create or replace function public.tc_trips_lock_owner() returns trigger language plpgsql as $$
begin
  if new.user_id is distinct from old.user_id then
    raise exception 'TRIP_OWNER_LOCKED' using errcode='42501', hint='소유권 이전은 아직 지원하지 않는다';
  end if;
  return new;
end $$;
drop trigger if exists tc_trips_lock_owner on public.trips;
create trigger tc_trips_lock_owner before update on public.trips
  for each row execute function public.tc_trips_lock_owner();

-- 여행이 생기면 소유자 멤버 행도 생긴다 — 멤버 목록에 주최자가 항상 보이고, 인원 수가 1부터 시작한다.
create or replace function public.tc_trips_owner_member() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  insert into public.trip_members(trip_id,user_id,role,status,joined_at)
  values(new.id,new.user_id,'OWNER','ACTIVE',now())
  on conflict (trip_id,user_id) do update set role='OWNER', status='ACTIVE', updated_at=now();
  return new;
end $$;
drop trigger if exists tc_trips_owner_member on public.trips;
create trigger tc_trips_owner_member after insert on public.trips
  for each row execute function public.tc_trips_owner_member();

create or replace function public.tc_touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end $$;
drop trigger if exists tc_trip_members_touch on public.trip_members;
create trigger tc_trip_members_touch before update on public.trip_members
  for each row execute function public.tc_touch_updated_at();

-- 기존 여행 전부에 소유자 멤버십을 채운다(§96). 몇 번 돌려도 같다.
insert into public.trip_members(trip_id,user_id,role,status,joined_at)
select t.id,t.user_id,'OWNER','ACTIVE',t.created_at from public.trips t
on conflict (trip_id,user_id) do update set role='OWNER', status='ACTIVE', updated_at=now();

-- ── RLS ─────────────────────────────────────────────────────────────────────

alter table public.trip_members enable row level security;
alter table public.trip_invites enable row level security;

-- 정책은 OR로 결합되므로 이름을 모르는 기존 허용 정책도 걷어낸 뒤 desired state를 만든다.
do $$ declare p record; begin
  for p in select policyname,tablename from pg_policies
           where schemaname='public' and tablename in ('trips','trip_members','trip_invites') loop
    execute format('drop policy %I on public.%I',p.policyname,p.tablename);
  end loop;
end $$;

-- trips: 읽기는 소유자 또는 활성 멤버 · 쓰기는 소유자 또는 EDITOR · 생성과 삭제는 소유자만
create policy "trips_member_select" on public.trips for select to authenticated
  using ((select auth.uid())=user_id or public.tc_trip_role(id) is not null);
create policy "trips_owner_insert" on public.trips for insert to authenticated
  with check ((select auth.uid())=user_id);
create policy "trips_editor_update" on public.trips for update to authenticated
  using ((select auth.uid())=user_id or public.tc_trip_role(id)='EDITOR')
  with check ((select auth.uid())=user_id or public.tc_trip_role(id)='EDITOR');
create policy "trips_owner_delete" on public.trips for delete to authenticated
  using ((select auth.uid())=user_id);

-- trip_members: 같은 여행의 멤버끼리 서로 보인다. **쓰기 정책은 없다** — 아래 RPC(security definer)만 쓴다.
create policy "trip_members_member_select" on public.trip_members for select to authenticated
  using (public.tc_trip_role(trip_id) is not null);

-- trip_invites: 소유자만 본다. 쓰기는 RPC만. (해시만 있어 보여도 링크를 만들 수는 없다)
create policy "trip_invites_owner_select" on public.trip_invites for select to authenticated
  using (public.tc_trip_role(trip_id)='OWNER');

revoke all on public.trip_members, public.trip_invites from anon, public;
grant select on public.trip_members, public.trip_invites to authenticated;

-- ── 동기화 RPC (멤버 인식) ──────────────────────────────────────────────────

-- sync_trip: 소유자와 EDITOR가 같은 행을 CAS로 갱신한다. VIEWER는 42501.
-- 행이 없으면 내 여행으로 새로 만든다 — 단, 이 여행에서 나갔거나 내보내진 사람의 로컬 사본은 만들지 않는다.
--
-- ⚠️ 조회와 잠금을 나눈다. RLS 아래에서 SELECT … FOR UPDATE는 **update 정책의 USING까지** 통과한 행만 돌려준다.
-- 잠금과 조회를 한 문장에 두면 VIEWER에게는 행이 "없는 것"이 되어 거절 대신 제 계정에 복제본을 만들어 버린다
-- (실제 PostgreSQL 테스트 test/rls/collaboration.sql에서 잡힌 사고). 먼저 잠금 없이 찾아 역할을 판정하고, 그다음 잠근다.
create or replace function public.sync_trip(p_client_id text,p_data jsonb,p_expected_revision bigint default null,p_force boolean default false)
returns table(applied boolean,conflict boolean,revision bigint,data jsonb,deleted_at timestamptz)
language plpgsql security invoker set search_path=public as $$
declare current_row public.trips%rowtype; v_role text; v_id public.trips.id%type;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select t.id into v_id from public.trips t
    where t.client_id=p_client_id and public.tc_trip_role(t.id) is not null
    order by (t.user_id=auth.uid()) desc, t.id limit 1;
  if v_id is null then
    if public.tc_was_member(p_client_id) then
      raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='이 여행에서 나갔거나 내보내졌다';
    end if;
    insert into public.trips(user_id,client_id,data,revision) values(auth.uid(),p_client_id,p_data,1)
    returning trips.revision,trips.data,trips.deleted_at into revision,data,deleted_at;
    return query select true,false,revision,data,deleted_at; return;
  end if;
  v_role := public.tc_trip_role(v_id);
  if v_role is distinct from 'OWNER' and v_role is distinct from 'EDITOR' then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='보기 권한으로는 저장할 수 없다';
  end if;
  select t.* into current_row from public.trips t where t.id=v_id for update;
  if not found then   -- 그 사이 역할이 내려갔다(update 정책에 걸림)
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='이 여행을 바꿀 권한이 없다';
  end if;
  if not p_force and (current_row.deleted_at is not null or p_expected_revision is distinct from current_row.revision) then
    return query select false,true,current_row.revision,current_row.data,current_row.deleted_at; return;
  end if;
  update public.trips set data=p_data,revision=current_row.revision+1,deleted_at=null,updated_at=now()
    where id=current_row.id returning trips.revision,trips.data,trips.deleted_at into revision,data,deleted_at;
  return query select true,false,revision,data,deleted_at;
end $$;

-- tombstone_trip: 삭제는 소유자만. 멤버가 부르면 42501 — 멤버는 leave_trip으로 나간다.
create or replace function public.tombstone_trip(p_client_id text,p_expected_revision bigint default null,p_force boolean default false)
returns table(applied boolean,conflict boolean,revision bigint,data jsonb,deleted_at timestamptz)
language plpgsql security invoker set search_path=public as $$
declare current_row public.trips%rowtype; v_id public.trips.id%type; v_owner uuid;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  -- 잠금 없이 먼저 찾는다 — FOR UPDATE는 update 정책을 못 넘는 VIEWER에게 행을 감춰 '이미 없음'으로 보이게 한다(위 sync_trip 참고)
  select t.id, t.user_id into v_id, v_owner from public.trips t
    where t.client_id=p_client_id and public.tc_trip_role(t.id) is not null
    order by (t.user_id=auth.uid()) desc, t.id limit 1;
  if v_id is null then return query select true,false,coalesce(p_expected_revision,0),null::jsonb,now(); return; end if;
  if v_owner<>auth.uid() then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='여행 삭제는 소유자만 — 멤버는 leave_trip으로 나간다';
  end if;
  select t.* into current_row from public.trips t where t.id=v_id for update;
  if not found then raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='이 여행을 바꿀 권한이 없다'; end if;
  if not p_force and p_expected_revision is distinct from current_row.revision then
    return query select false,true,current_row.revision,current_row.data,current_row.deleted_at; return;
  end if;
  update public.trips set revision=current_row.revision+1,deleted_at=now(),updated_at=now()
    where id=current_row.id returning trips.revision,trips.data,trips.deleted_at into revision,data,deleted_at;
  return query select true,false,revision,data,deleted_at;
end $$;

-- ── 멤버 조회 RPC ───────────────────────────────────────────────────────────

-- 내가 볼 수 있는 여행 전부의 역할·인원. 로그인 직후와 목록 화면에서 한 번 부른다(여행 수만큼 부르지 않는다).
-- trip_id는 text로 준다 — 클라이언트는 client_id로만 여행을 찾고, trips.id 타입(uuid/bigint)에 매이지 않는다.
create or replace function public.my_trip_roles()
returns table(client_id text, trip_id text, role text, member_count int, owner boolean)
language sql stable security invoker set search_path=public as $$
  select t.client_id, t.id::text, public.tc_trip_role(t.id),
         (select count(*)::int from public.trip_members m where m.trip_id=t.id and m.status='ACTIVE'),
         t.user_id=auth.uid()
    from public.trips t
   where t.deleted_at is null and public.tc_trip_role(t.id) is not null
   order by (t.user_id=auth.uid()) desc, t.id
$$;

-- 한 여행의 활성 멤버. 주최자가 먼저, 그다음 참여한 순서.
create or replace function public.list_trip_members(p_client_id text)
returns table(id bigint, user_id uuid, role text, status text, display_name text, joined_at timestamptz, me boolean)
language sql stable security invoker set search_path=public as $$
  select m.id, m.user_id, m.role, m.status, m.display_name, m.joined_at, m.user_id=auth.uid()
    from public.trip_members m
   where m.trip_id=(select t.id from public.trips t
                     where t.client_id=p_client_id and public.tc_trip_role(t.id) is not null
                     order by (t.user_id=auth.uid()) desc, t.id limit 1)
     and m.status='ACTIVE'
   order by (m.role='OWNER') desc, m.joined_at nulls last, m.id
$$;

-- ── 초대 RPC ────────────────────────────────────────────────────────────────

-- 소유자만. 토큰은 여기서 **한 번만** 돌려준다 — 저장은 해시로만.
create or replace function public.create_trip_invite(p_client_id text, p_role text, p_hours int default 168, p_max_uses int default null)
returns table(id bigint, token text, role text, expires_at timestamptz)
language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_trip public.trips%rowtype; v_token text; v_hours int;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  if p_role is null or p_role not in ('EDITOR','VIEWER') then
    raise exception 'INVALID_ROLE' using errcode='22023', hint='초대 역할은 EDITOR 또는 VIEWER';
  end if;
  select t.* into v_trip from public.trips t
    where t.client_id=p_client_id and t.user_id=v_uid and t.deleted_at is null limit 1;
  if not found then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='초대 링크는 소유자만 만들 수 있다';
  end if;
  v_hours := least(greatest(coalesce(p_hours,168),1),24*30);   -- 1시간 ~ 30일
  -- 192비트 난수 → URL-safe base64 (32자). 추측할 수 없어야 raw trip id로는 참여할 수 없다(§5).
  v_token := rtrim(translate(encode(extensions.gen_random_bytes(24),'base64'),'+/','-_'),'=');
  return query insert into public.trip_invites(trip_id,token_hash,role,created_by,expires_at,max_uses)
    values(v_trip.id, encode(extensions.digest(v_token,'sha256'),'hex'), p_role, v_uid,
           now()+make_interval(hours=>v_hours), p_max_uses)
    returning trip_invites.id, v_token, trip_invites.role, trip_invites.expires_at;
end $$;

-- 소유자의 초대 목록 (최근 50개). active=false인 것은 만료·취소·소진.
create or replace function public.list_trip_invites(p_client_id text)
returns table(id bigint, role text, expires_at timestamptz, use_count int, max_uses int, created_at timestamptz, active boolean)
language sql stable security invoker set search_path=public as $$
  select i.id, i.role, i.expires_at, i.use_count, i.max_uses, i.created_at,
         (i.revoked_at is null and i.expires_at>now() and (i.max_uses is null or i.use_count<i.max_uses))
    from public.trip_invites i
   where i.trip_id=(select t.id from public.trips t where t.client_id=p_client_id and t.user_id=auth.uid() limit 1)
   order by i.created_at desc
   limit 50
$$;

-- 취소. 두 번 눌러도 같다(첫 취소 시각을 유지).
create or replace function public.revoke_trip_invite(p_invite_id bigint) returns boolean
language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_n int;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  update public.trip_invites i set revoked_at=coalesce(i.revoked_at,now())
   where i.id=p_invite_id and exists(select 1 from public.trips t where t.id=i.trip_id and t.user_id=v_uid);
  get diagnostics v_n=row_count;
  return v_n>0;
end $$;

-- 초대 미리보기 — **로그인 전에도** 부른다(anon). 링크가 유출돼도 여기까지만 보인다(§6):
-- 여행 이름·시작일·일수·역할. 일정 본문·예약·장소는 참여한 뒤 RLS 아래에서만 읽힌다.
create or replace function public.invite_preview(p_token text)
returns table(valid boolean, reason text, trip_name text, start_date text, day_count int, role text, expires_at timestamptz, already_member boolean)
language plpgsql security definer set search_path=public as $$
declare v_inv public.trip_invites%rowtype; v_trip public.trips%rowtype; v_uid uuid := auth.uid();
begin
  if p_token is null or length(p_token)<16 or length(p_token)>128 then
    return query select false,'INVALID',null::text,null::text,null::int,null::text,null::timestamptz,false; return;
  end if;
  select i.* into v_inv from public.trip_invites i
    where i.token_hash=encode(extensions.digest(p_token,'sha256'),'hex');
  if not found then
    return query select false,'INVALID',null::text,null::text,null::int,null::text,null::timestamptz,false; return;
  end if;
  select t.* into v_trip from public.trips t where t.id=v_inv.trip_id;
  return query select
    (v_inv.revoked_at is null and v_inv.expires_at>now()
      and (v_inv.max_uses is null or v_inv.use_count<v_inv.max_uses) and v_trip.deleted_at is null),
    case when v_trip.deleted_at is not null then 'TRIP_DELETED'
         when v_inv.revoked_at is not null then 'REVOKED'
         when v_inv.expires_at<=now() then 'EXPIRED'
         when v_inv.max_uses is not null and v_inv.use_count>=v_inv.max_uses then 'EXHAUSTED'
         else 'OK' end,
    coalesce(v_trip.data->>'name','여행'),
    coalesce(v_trip.data->>'start',''),
    case when jsonb_typeof(v_trip.data->'days')='array' then jsonb_array_length(v_trip.data->'days') else 0 end,
    v_inv.role, v_inv.expires_at,
    (v_uid is not null and (v_trip.user_id=v_uid or exists(
       select 1 from public.trip_members m where m.trip_id=v_trip.id and m.user_id=v_uid and m.status='ACTIVE')));
end $$;

-- 초대 수락 — 로그인 사용자만. 여기서만 멤버십이 생긴다(§67).
-- 같은 요청을 두 번 받아도 결과가 같다(§74): 이미 활성 멤버면 그대로 돌려주고 사용 횟수도 다시 세지 않는다.
create or replace function public.accept_trip_invite(p_token text, p_display_name text default null)
returns table(ok boolean, reason text, client_id text, trip_name text, role text, already_member boolean)
language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_inv public.trip_invites%rowtype; v_trip public.trips%rowtype;
        v_mem public.trip_members%rowtype; v_name text; v_has_mem boolean;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  v_name := nullif(left(btrim(coalesce(p_display_name,'')),40),'');
  select i.* into v_inv from public.trip_invites i
    where i.token_hash=encode(extensions.digest(coalesce(p_token,''),'sha256'),'hex') for update;
  if not found then return query select false,'INVALID',null::text,null::text,null::text,false; return; end if;
  select t.* into v_trip from public.trips t where t.id=v_inv.trip_id for update;
  if v_trip.deleted_at is not null then
    return query select false,'TRIP_DELETED',null::text,null::text,null::text,false; return;
  end if;
  -- 소유자가 제 링크를 열었다 — 이미 여행 안이다.
  if v_trip.user_id=v_uid then
    return query select true,'OK',v_trip.client_id,coalesce(v_trip.data->>'name','여행'),'OWNER',true; return;
  end if;
  select m.* into v_mem from public.trip_members m where m.trip_id=v_trip.id and m.user_id=v_uid for update;
  v_has_mem := found;
  if v_has_mem and v_mem.status='ACTIVE' then
    return query select true,'OK',v_trip.client_id,coalesce(v_trip.data->>'name','여행'),v_mem.role,true; return;
  end if;
  -- 링크의 유효성은 **새 참여**에만 따진다(이미 멤버면 위에서 끝났다).
  if v_inv.revoked_at is not null then return query select false,'REVOKED',null::text,null::text,null::text,false; return; end if;
  if v_inv.expires_at<=now() then return query select false,'EXPIRED',null::text,null::text,null::text,false; return; end if;
  if v_inv.max_uses is not null and v_inv.use_count>=v_inv.max_uses then
    return query select false,'EXHAUSTED',null::text,null::text,null::text,false; return;
  end if;
  -- 소유자가 내보낸 사람은 **그 전에 만든** 링크로는 다시 못 들어온다(§70). 새 링크를 받으면 된다.
  if v_has_mem and v_mem.status='REMOVED' and v_mem.updated_at>=v_inv.created_at then
    return query select false,'REMOVED',null::text,null::text,null::text,false; return;
  end if;
  if v_has_mem then
    update public.trip_members m
       set role=v_inv.role, status='ACTIVE', display_name=coalesce(v_name,m.display_name),
           invited_by=v_inv.created_by, joined_at=now()
     where m.id=v_mem.id;
  else
    insert into public.trip_members(trip_id,user_id,role,status,display_name,invited_by,joined_at)
    values(v_trip.id,v_uid,v_inv.role,'ACTIVE',v_name,v_inv.created_by,now());
  end if;
  update public.trip_invites i set use_count=i.use_count+1 where i.id=v_inv.id;
  return query select true,'OK',v_trip.client_id,coalesce(v_trip.data->>'name','여행'),v_inv.role,false;
end $$;

-- ── 멤버 관리 RPC ───────────────────────────────────────────────────────────

-- 나가기 — 소유자가 아닌 멤버만(§71). 이미 나갔으면 그대로 true(두 번 눌러도 같다).
create or replace function public.leave_trip(p_client_id text) returns boolean
language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_trip public.trips%rowtype;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  -- 나가기는 남의 여행에만 의미가 있다 — 같은 client_id를 내가 소유한 것이 있어도 그쪽을 고르지 않는다.
  select t.* into v_trip from public.trips t
   where t.client_id=p_client_id
     and exists(select 1 from public.trip_members m where m.trip_id=t.id and m.user_id=v_uid and m.status='ACTIVE')
   order by (t.user_id=v_uid) asc, t.id limit 1;
  if not found then return true; end if;
  if v_trip.user_id=v_uid then
    raise exception 'OWNER_CANNOT_LEAVE' using errcode='42501', hint='소유자는 나갈 수 없다 — 여행을 삭제하거나 (다음 단계에서) 소유권을 넘긴다';
  end if;
  update public.trip_members m set status='LEFT' where m.trip_id=v_trip.id and m.user_id=v_uid;
  return true;
end $$;

-- 역할 변경(SET_ROLE)·내보내기(REMOVE)는 소유자만, 이름 바꾸기(RENAME)는 소유자 또는 본인.
-- 소유자 자신의 행(OWNER)은 바꾸거나 내보낼 수 없다.
create or replace function public.manage_trip_member(p_member_id bigint, p_action text, p_value text default null) returns boolean
language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_mem public.trip_members%rowtype; v_owner uuid;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  select m.* into v_mem from public.trip_members m where m.id=p_member_id for update;
  if not found then return false; end if;
  select t.user_id into v_owner from public.trips t where t.id=v_mem.trip_id;
  if p_action='RENAME' then
    if v_uid<>v_owner and v_uid<>v_mem.user_id then
      raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='이름은 본인이나 소유자만 바꾼다';
    end if;
    update public.trip_members m set display_name=nullif(left(btrim(coalesce(p_value,'')),40),'') where m.id=v_mem.id;
    return true;
  end if;
  if v_uid<>v_owner then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='역할 변경과 내보내기는 소유자만';
  end if;
  if v_mem.role='OWNER' then
    raise exception 'OWNER_LOCKED' using errcode='42501', hint='소유자 자신의 역할은 바꾸거나 내보낼 수 없다';
  end if;
  if p_action='SET_ROLE' then
    if p_value is null or p_value not in ('EDITOR','VIEWER') then
      raise exception 'INVALID_ROLE' using errcode='22023', hint='역할은 EDITOR 또는 VIEWER';
    end if;
    update public.trip_members m set role=p_value where m.id=v_mem.id;
    return true;
  elsif p_action='REMOVE' then
    update public.trip_members m set status='REMOVED' where m.id=v_mem.id and m.status<>'REMOVED';
    return true;
  end if;
  raise exception 'INVALID_ACTION' using errcode='22023', hint='SET_ROLE · REMOVE · RENAME';
end $$;

-- ── 권한 ────────────────────────────────────────────────────────────────────
-- 함수는 기본적으로 public이 실행할 수 있다 — security definer는 특히 반드시 거둬야 한다.

revoke all on function public.sync_trip(text,jsonb,bigint,boolean) from public,anon;
revoke all on function public.tombstone_trip(text,bigint,boolean) from public,anon;
revoke all on function public.my_trip_roles() from public,anon;
revoke all on function public.list_trip_members(text) from public,anon;
revoke all on function public.create_trip_invite(text,text,int,int) from public,anon;
revoke all on function public.list_trip_invites(text) from public,anon;
revoke all on function public.revoke_trip_invite(bigint) from public,anon;
revoke all on function public.invite_preview(text) from public;
revoke all on function public.accept_trip_invite(text,text) from public,anon;
revoke all on function public.leave_trip(text) from public,anon;
revoke all on function public.manage_trip_member(bigint,text,text) from public,anon;

grant execute on function public.sync_trip(text,jsonb,bigint,boolean) to authenticated;
grant execute on function public.tombstone_trip(text,bigint,boolean) to authenticated;
grant execute on function public.my_trip_roles() to authenticated;
grant execute on function public.list_trip_members(text) to authenticated;
grant execute on function public.create_trip_invite(text,text,int,int) to authenticated;
grant execute on function public.list_trip_invites(text) to authenticated;
grant execute on function public.revoke_trip_invite(bigint) to authenticated;
-- 미리보기만 로그인 전에도 허용 — "어떤 여행에 초대받았는지"를 보고 로그인할지 정한다.
grant execute on function public.invite_preview(text) to anon, authenticated;
grant execute on function public.accept_trip_invite(text,text) to authenticated;
grant execute on function public.leave_trip(text) to authenticated;
grant execute on function public.manage_trip_member(bigint,text,text) to authenticated;

commit;
