-- Desired Trip Canvas schema. Apply only after the preflight in docs/supabase-migrations.md.
begin;

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  client_id text not null,
  data jsonb not null,
  revision bigint not null default 1 check (revision > 0),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, client_id)
);

create table if not exists public.trip_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  client_id text not null,
  name text not null default '',
  data jsonb not null,
  source_revision bigint check (source_revision is null or source_revision > 0),
  created_at timestamptz not null default now()
);

-- Existing installations fail safely here when null owners or duplicate client IDs exist.
do $$
begin
  if exists(select 1 from public.trips where user_id is null) then raise exception 'trips.user_id contains nulls'; end if;
  if exists(select 1 from public.trip_snapshots where user_id is null) then raise exception 'trip_snapshots.user_id contains nulls'; end if;
  if exists(select 1 from public.trips group by user_id,client_id having count(*)>1) then raise exception 'duplicate trips (user_id,client_id)'; end if;
end $$;

alter table public.trips add column if not exists revision bigint not null default 1;
alter table public.trips add column if not exists deleted_at timestamptz;
alter table public.trips add column if not exists created_at timestamptz not null default now();
alter table public.trips add column if not exists updated_at timestamptz not null default now();
alter table public.trip_snapshots add column if not exists user_id uuid default auth.uid() references auth.users(id) on delete cascade;
alter table public.trip_snapshots add column if not exists source_revision bigint;
alter table public.trips alter column user_id set not null;
alter table public.trip_snapshots alter column user_id set not null;
alter table public.trips alter column user_id set default auth.uid();
alter table public.trip_snapshots alter column user_id set default auth.uid();

create unique index if not exists trips_user_client_uidx on public.trips(user_id,client_id);
create index if not exists trips_user_updated_idx on public.trips(user_id,updated_at desc);
create index if not exists snapshots_user_client_created_idx on public.trip_snapshots(user_id,client_id,created_at desc);

alter table public.trips enable row level security;
alter table public.trip_snapshots enable row level security;

-- 정책은 OR로 결합되므로 이름을 모르는 기존 허용 정책도 제거한 뒤 desired state를 만든다.
do $$ declare p record; begin
  for p in select policyname,tablename from pg_policies where schemaname='public' and tablename in ('trips','trip_snapshots') loop
    execute format('drop policy %I on public.%I',p.policyname,p.tablename);
  end loop;
end $$;

create policy "trips_owner_select" on public.trips for select to authenticated using ((select auth.uid())=user_id);
create policy "trips_owner_insert" on public.trips for insert to authenticated with check ((select auth.uid())=user_id);
create policy "trips_owner_update" on public.trips for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "trips_owner_delete" on public.trips for delete to authenticated using ((select auth.uid())=user_id);

create policy "snapshots_owner_select" on public.trip_snapshots for select to authenticated using ((select auth.uid())=user_id);
create policy "snapshots_owner_insert" on public.trip_snapshots for insert to authenticated with check ((select auth.uid())=user_id);
create policy "snapshots_owner_update" on public.trip_snapshots for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "snapshots_owner_delete" on public.trip_snapshots for delete to authenticated using ((select auth.uid())=user_id);

revoke all on public.trips,public.trip_snapshots from anon;
grant select,insert,update,delete on public.trips,public.trip_snapshots to authenticated;

create or replace function public.sync_trip(p_client_id text,p_data jsonb,p_expected_revision bigint default null,p_force boolean default false)
returns table(applied boolean,conflict boolean,revision bigint,data jsonb,deleted_at timestamptz)
language plpgsql security invoker set search_path=public as $$
declare current_row public.trips%rowtype;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into current_row from public.trips where user_id=auth.uid() and client_id=p_client_id for update;
  if not found then
    insert into public.trips(user_id,client_id,data,revision) values(auth.uid(),p_client_id,p_data,1)
    returning trips.revision,trips.data,trips.deleted_at into revision,data,deleted_at;
    return query select true,false,revision,data,deleted_at; return;
  end if;
  if not p_force and (current_row.deleted_at is not null or p_expected_revision is distinct from current_row.revision) then
    return query select false,true,current_row.revision,current_row.data,current_row.deleted_at; return;
  end if;
  update public.trips set data=p_data,revision=current_row.revision+1,deleted_at=null,updated_at=now()
    where id=current_row.id returning trips.revision,trips.data,trips.deleted_at into revision,data,deleted_at;
  return query select true,false,revision,data,deleted_at;
end $$;

create or replace function public.tombstone_trip(p_client_id text,p_expected_revision bigint default null,p_force boolean default false)
returns table(applied boolean,conflict boolean,revision bigint,data jsonb,deleted_at timestamptz)
language plpgsql security invoker set search_path=public as $$
declare current_row public.trips%rowtype;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into current_row from public.trips where user_id=auth.uid() and client_id=p_client_id for update;
  if not found then return query select true,false,coalesce(p_expected_revision,0),null::jsonb,now(); return; end if;
  if not p_force and p_expected_revision is distinct from current_row.revision then
    return query select false,true,current_row.revision,current_row.data,current_row.deleted_at; return;
  end if;
  update public.trips set revision=current_row.revision+1,deleted_at=now(),updated_at=now()
    where id=current_row.id returning trips.revision,trips.data,trips.deleted_at into revision,data,deleted_at;
  return query select true,false,revision,data,deleted_at;
end $$;

revoke all on function public.sync_trip(text,jsonb,bigint,boolean) from public,anon;
revoke all on function public.tombstone_trip(text,bigint,boolean) from public,anon;
grant execute on function public.sync_trip(text,jsonb,bigint,boolean) to authenticated;
grant execute on function public.tombstone_trip(text,bigint,boolean) to authenticated;

commit;
