-- 추천 반응 기록 (Adaptive Travel OS). 기기가 둘 이상이 되면서 필요해졌다:
-- iPhone에서 건너뛴 제안이 다른 기기에서 그대로 다시 올라오면 "거절한 걸 반복하지 않는다"가 깨진다.
--
-- 여행 문서(trips.data)에 넣지 않는다 — 추천은 여행 데이터가 아니고, 공유 링크·내보내기에 섞이면 안 된다.
-- 수락해서 일정이 바뀐 결과만 trips.data에 남는다.
--
-- 같은 (사용자, 여행, 날짜, 제안키)는 한 행이다 → 같은 요청을 두 번 보내도 결과가 같다(idempotent).
begin;

create table if not exists public.suggestion_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  trip_client_id text not null,
  day_iso date not null,
  suggestion_key text not null,
  action text not null check (action in ('ACCEPTED','SKIPPED','DISMISSED','REPLACED')),
  source text not null default 'unknown',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, trip_client_id, day_iso, suggestion_key)
);

alter table public.suggestion_feedback add column if not exists source text not null default 'unknown';
alter table public.suggestion_feedback add column if not exists updated_at timestamptz not null default now();

-- 거절은 '그날 하루' 유효하다 → 조회는 항상 (여행, 날짜)로 들어온다.
create index if not exists suggestion_feedback_lookup_idx
  on public.suggestion_feedback(user_id, trip_client_id, day_iso);
-- 오래된 기록은 학습용으로만 의미가 있어 조회 경로에서 비켜 둔다.
create index if not exists suggestion_feedback_created_idx
  on public.suggestion_feedback(user_id, created_at desc);

alter table public.suggestion_feedback enable row level security;

-- 이름을 모르는 기존 허용 정책까지 걷어내고 desired state를 만든다 (정책은 OR로 결합된다).
do $$ declare p record; begin
  for p in select policyname from pg_policies where schemaname='public' and tablename='suggestion_feedback' loop
    execute format('drop policy %I on public.suggestion_feedback', p.policyname);
  end loop;
end $$;

create policy "suggestion_feedback_owner_select" on public.suggestion_feedback
  for select to authenticated using ((select auth.uid())=user_id);
create policy "suggestion_feedback_owner_insert" on public.suggestion_feedback
  for insert to authenticated with check ((select auth.uid())=user_id);
create policy "suggestion_feedback_owner_update" on public.suggestion_feedback
  for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "suggestion_feedback_owner_delete" on public.suggestion_feedback
  for delete to authenticated using ((select auth.uid())=user_id);

revoke all on public.suggestion_feedback from anon;
grant select,insert,update,delete on public.suggestion_feedback to authenticated;

commit;
