-- 함께하기 3단계 — 코멘트 · 활동 기록 · 실시간 전달.
--
-- 코멘트(§14)는 후보 장소에 붙는 짧은 의견이다. 채팅이 아니다(§15) — 장소 중심 토론만. @mention 없음(§52).
-- 활동 기록(§37~§39)은 "누가 무엇을 했는가"의 **의미 있는** 변경만 남긴다. 트리거가 쓴다 —
-- 1·2단계 RPC 본문을 건드리지 않고, 어떤 경로로 바뀌든 같은 기록이 남는다.
-- 실시간(§40·§41)은 **전달 수단**일 뿐이다. source of truth는 DB고, 클라이언트는 이벤트를 받으면
-- 그 내용을 믿지 않고 RPC로 다시 읽는다. 실시간이 죽어도 앱은 그대로 돈다(탭 복귀 시 pull이 폴백).
--
-- 접근 경계는 여기(RLS)다. 두 테이블 모두 읽기는 활성 멤버만, 쓰기 정책은 없고 RPC·트리거만 쓴다.

-- ── 테이블 ──────────────────────────────────────────────────────────────────

do $$ declare t text; begin
  select format_type(a.atttypid, a.atttypmod) into t
    from pg_attribute a where a.attrelid='public.trips'::regclass and a.attname='id';
  execute format($sql$
    create table if not exists public.trip_comments (
      id bigint generated by default as identity primary key,
      trip_id %1$s not null references public.trips(id) on delete cascade,
      -- 코멘트는 후보에만 붙는다. 문서 안 장소에는 안정적인 id가 없어 붙일 곳이 없다(scheduled_ref와 같은 이유).
      candidate_id bigint not null references public.trip_candidates(id) on delete cascade,
      user_id uuid not null references auth.users(id) on delete cascade,
      body text not null check (btrim(body) <> '' and length(body) <= 500),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    )$sql$, t);
  execute format($sql$
    create table if not exists public.trip_activity (
      id bigint generated by default as identity primary key,
      trip_id %1$s not null references public.trips(id) on delete cascade,
      -- 누가. 계정이 지워지면 null — 기록은 남고 이름표만 '멤버'가 된다.
      actor_id uuid references auth.users(id) on delete set null,
      kind text not null check (kind in (
        'MEMBER_JOINED','MEMBER_LEFT','MEMBER_REMOVED',
        'CANDIDATE_PROPOSED','CANDIDATE_SCHEDULED','REACTION','COMMENT_ADDED',
        'SCHEDULE_CHANGED','BOOKING_ADDED')),
      -- 문장을 만들 재료(후보 이름·반응·일차 등). 화면 문장은 클라이언트(collab.js activityText)가 만든다(§39).
      subject jsonb not null default '{}'::jsonb,
      created_at timestamptz not null default now()
    )$sql$, t);
end $$;

create index if not exists trip_comments_cand_idx on public.trip_comments(candidate_id, created_at);
create index if not exists trip_activity_trip_idx on public.trip_activity(trip_id, id desc);

drop trigger if exists trip_comments_touch on public.trip_comments;
create trigger trip_comments_touch before update on public.trip_comments
  for each row execute function public.tc_touch_updated_at();

-- ── 1단계 트리거 함수의 search_path 고정 (Supabase 린터 WARN) ────────────────
-- 직접 호출은 PostgreSQL이 막지만(trigger 반환형), 본문을 그대로 두고 search_path만 못 박는다.

create or replace function public.tc_trips_lock_owner() returns trigger
language plpgsql set search_path=public as $$
begin
  if new.user_id is distinct from old.user_id then
    raise exception 'TRIP_OWNER_LOCKED' using errcode='42501', hint='소유권 이전은 아직 지원하지 않는다';
  end if;
  return new;
end $$;

create or replace function public.tc_touch_updated_at() returns trigger
language plpgsql set search_path=public as $$
begin new.updated_at=now(); return new; end $$;

-- ── 활동 기록 — 트리거가 쓴다 ───────────────────────────────────────────────

-- 한 줄 넣기. 트리거 안에서만 불린다 — 클라이언트는 실행 권한이 없다.
create or replace function public.tc_log_activity(p_trip_id public.trips.id%type, p_kind text, p_subject jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public as $$
begin
  insert into public.trip_activity(trip_id, actor_id, kind, subject)
  values (p_trip_id, auth.uid(), p_kind, coalesce(p_subject,'{}'::jsonb));
end $$;

-- 후보: 담기 · 일정에 넣기. 빼기는 기록하지 않는다(§38 — 의미 있는 변경만).
create or replace function public.tc_act_candidates() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if tg_op='INSERT' then
    perform public.tc_log_activity(new.trip_id,'CANDIDATE_PROPOSED',jsonb_build_object('title',new.title,'candidate_id',new.id));
  elsif tg_op='UPDATE' and new.status='SCHEDULED' and old.status is distinct from 'SCHEDULED' then
    perform public.tc_log_activity(new.trip_id,'CANDIDATE_SCHEDULED',jsonb_build_object('title',new.title,'candidate_id',new.id,'ref',new.scheduled_ref));
  end if;
  return null;
end $$;
drop trigger if exists tc_act_candidates on public.trip_candidates;
create trigger tc_act_candidates after insert or update on public.trip_candidates
  for each row execute function public.tc_act_candidates();

-- 반응: 남기기·바꾸기만. 거두기(delete)는 기록하지 않는다.
-- 제안자에게 자동으로 붙는 MUST(add_trip_candidate)는 같은 트랜잭션이라 created_at이 같다 — 그건 뺀다.
create or replace function public.tc_act_reactions() returns trigger
language plpgsql security definer set search_path=public as $$
declare v_cand public.trip_candidates%rowtype;
begin
  select c.* into v_cand from public.trip_candidates c where c.id=new.candidate_id;
  if not found then return null; end if;
  if v_cand.proposed_by=new.user_id and v_cand.created_at>=now()-interval '1 second' then return null; end if;
  if tg_op='UPDATE' and old.reaction=new.reaction then return null; end if;
  perform public.tc_log_activity(v_cand.trip_id,'REACTION',
    jsonb_build_object('title',v_cand.title,'candidate_id',v_cand.id,'reaction',new.reaction));
  return null;
end $$;
drop trigger if exists tc_act_reactions on public.candidate_reactions;
create trigger tc_act_reactions after insert or update on public.candidate_reactions
  for each row execute function public.tc_act_reactions();

create or replace function public.tc_act_comments() returns trigger
language plpgsql security definer set search_path=public as $$
declare v_title text;
begin
  select c.title into v_title from public.trip_candidates c where c.id=new.candidate_id;
  perform public.tc_log_activity(new.trip_id,'COMMENT_ADDED',
    jsonb_build_object('title',coalesce(v_title,''),'candidate_id',new.candidate_id,'excerpt',left(new.body,60)));
  return null;
end $$;
drop trigger if exists tc_act_comments on public.trip_comments;
create trigger tc_act_comments after insert on public.trip_comments
  for each row execute function public.tc_act_comments();

-- 멤버: 참여 · 나감 · 내보내짐. 소유자 행(여행 생성 트리거·백필)은 기록하지 않는다 — 혼자 만든 여행에 "참여했어요"가 뜨면 이상하다.
-- MEMBER_REMOVED의 actor는 내보낸 소유자고, 누가 내보내졌는지는 subject.member_id로 남긴다.
create or replace function public.tc_act_members() returns trigger
language plpgsql security definer set search_path=public as $$
declare v_kind text;
begin
  if new.role='OWNER' then return null; end if;
  if tg_op='INSERT' then
    if new.status='ACTIVE' then v_kind:='MEMBER_JOINED'; end if;
  elsif new.status is distinct from old.status then
    if new.status='ACTIVE' then v_kind:='MEMBER_JOINED';
    elsif new.status='LEFT' then v_kind:='MEMBER_LEFT';
    elsif new.status='REMOVED' then v_kind:='MEMBER_REMOVED';
    end if;
  end if;
  if v_kind is null then return null; end if;
  perform public.tc_log_activity(new.trip_id, v_kind, jsonb_build_object('member_id',new.user_id,'role',new.role));
  return null;
end $$;
drop trigger if exists tc_act_members on public.trip_members;
create trigger tc_act_members after insert or update on public.trip_members
  for each row execute function public.tc_act_members();

-- 여행 문서: 일정 변경 · 예약 추가. **다른 활성 멤버가 있을 때만** 남긴다 — 혼자 쓰는 여행의 저장마다
-- 행을 쌓고 실시간으로 내보낼 이유가 없다(§95). 문서 저장은 잦으므로 여행당 최근 300건만 남긴다.
-- 같은 사람의 연속 저장을 여기서 합치지 않는 이유: 행을 UPDATE하면 실시간 INSERT 구독자가 못 받는다.
-- 읽기 쉬운 묶음은 화면(collab.js condenseActivity)이 만든다(§39).
create or replace function public.tc_act_trips() returns trigger
language plpgsql security definer set search_path=public as $$
declare v_old int; v_new int; v_kind text; v_subject jsonb;
begin
  if new.deleted_at is not null then return null; end if;
  if not exists (select 1 from public.trip_members m
                  where m.trip_id=new.id and m.user_id<>new.user_id and m.status='ACTIVE') then
    return null;
  end if;
  v_old := case when jsonb_typeof(old.data->'bookings')='array' then jsonb_array_length(old.data->'bookings') else 0 end;
  v_new := case when jsonb_typeof(new.data->'bookings')='array' then jsonb_array_length(new.data->'bookings') else 0 end;
  if v_new > v_old then
    v_kind := 'BOOKING_ADDED'; v_subject := jsonb_build_object('count', v_new - v_old);
  else
    v_kind := 'SCHEDULE_CHANGED'; v_subject := jsonb_build_object('revision', new.revision);
  end if;
  perform public.tc_log_activity(new.id, v_kind, v_subject);
  delete from public.trip_activity a
   where a.trip_id=new.id
     and a.id < coalesce((select x.id from public.trip_activity x where x.trip_id=new.id order by x.id desc offset 300 limit 1), 0);
  return null;
end $$;
drop trigger if exists tc_act_trips on public.trips;
create trigger tc_act_trips after update of data on public.trips
  for each row when (old.data is distinct from new.data) execute function public.tc_act_trips();

-- ── RLS ─────────────────────────────────────────────────────────────────────

alter table public.trip_comments enable row level security;
alter table public.trip_activity enable row level security;

drop policy if exists "trip_comments_member_select" on public.trip_comments;
create policy "trip_comments_member_select" on public.trip_comments for select to authenticated
  using (public.tc_trip_role(trip_id) is not null);

drop policy if exists "trip_activity_member_select" on public.trip_activity;
create policy "trip_activity_member_select" on public.trip_activity for select to authenticated
  using (public.tc_trip_role(trip_id) is not null);

revoke all on public.trip_comments, public.trip_activity from anon, authenticated, public;
grant select on public.trip_comments, public.trip_activity to authenticated;

-- ── 코멘트 RPC ──────────────────────────────────────────────────────────────

-- 코멘트는 의견이다 — 보기 권한도 남긴다(반응과 같은 규칙). 멤버가 아니면 42501.
create or replace function public.add_candidate_comment(p_candidate_id bigint, p_body text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_cand public.trip_candidates%rowtype; v_body text; v_id bigint;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  v_body := nullif(left(btrim(coalesce(p_body,'')), 500), '');
  if v_body is null then raise exception 'BODY_REQUIRED' using errcode='22023', hint='빈 코멘트는 남길 수 없다'; end if;
  select c.* into v_cand from public.trip_candidates c where c.id=p_candidate_id;
  if not found or public.tc_trip_role(v_cand.trip_id) is null then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='이 여행의 멤버가 아니다';
  end if;
  insert into public.trip_comments(trip_id, candidate_id, user_id, body)
  values (v_cand.trip_id, v_cand.id, v_uid, v_body) returning id into v_id;
  return v_id;
end $$;

-- 지우기는 쓴 사람이나 주최자만. 이미 없으면 false(두 번 눌러도 같다).
create or replace function public.delete_candidate_comment(p_comment_id bigint)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_cm public.trip_comments%rowtype; v_owner uuid;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  select cm.* into v_cm from public.trip_comments cm where cm.id=p_comment_id for update;
  if not found then return false; end if;
  if public.tc_trip_role(v_cm.trip_id) is null then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='이 여행의 멤버가 아니다';
  end if;
  select t.user_id into v_owner from public.trips t where t.id=v_cm.trip_id;
  if v_uid<>v_cm.user_id and v_uid<>v_owner then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='코멘트는 쓴 사람이나 주최자만 지운다';
  end if;
  delete from public.trip_comments cm where cm.id=v_cm.id;
  return true;
end $$;

create or replace function public.list_candidate_comments(p_candidate_id bigint)
returns table(id bigint, body text, author_label text, mine boolean, created_at timestamptz)
language sql stable security invoker set search_path=public as $$
  select cm.id, cm.body, public.tc_member_label(cm.trip_id, cm.user_id), cm.user_id=auth.uid(), cm.created_at
    from public.trip_comments cm
   where cm.candidate_id=p_candidate_id
   order by cm.created_at, cm.id
$$;

-- list_trip_candidates에 comment_count를 더한다. 반환형이 바뀌므로 create or replace로는 안 되고 지웠다 만든다.
drop function if exists public.list_trip_candidates(text);
create function public.list_trip_candidates(p_client_id text)
returns table(id bigint, title text, place_id text, lat double precision, lng double precision,
              addr text, note text, url text, status text, scheduled_ref text,
              proposed_by_label text, mine boolean, my_reaction text,
              must_count int, ok_count int, pass_count int, reactions jsonb, comment_count int, created_at timestamptz)
language sql stable security invoker set search_path=public as $$
  with trip as (
    select t.id from public.trips t
     where t.client_id=p_client_id and t.deleted_at is null and public.tc_trip_role(t.id) is not null
     order by (t.user_id=auth.uid()) desc, t.id limit 1
  )
  select c.id, c.title, c.place_id, c.lat, c.lng, c.addr, c.note, c.url, c.status, c.scheduled_ref,
         public.tc_member_label(c.trip_id, c.proposed_by), c.proposed_by=auth.uid(),
         (select r.reaction from public.candidate_reactions r where r.candidate_id=c.id and r.user_id=auth.uid()),
         (select count(*)::int from public.candidate_reactions r where r.candidate_id=c.id and r.reaction='MUST'),
         (select count(*)::int from public.candidate_reactions r where r.candidate_id=c.id and r.reaction='OK'),
         (select count(*)::int from public.candidate_reactions r where r.candidate_id=c.id and r.reaction='PASS'),
         coalesce((select jsonb_agg(jsonb_build_object(
                     'name', public.tc_member_label(c.trip_id, r.user_id),
                     'reaction', r.reaction,
                     'me', r.user_id=auth.uid()) order by r.created_at, r.id)
                     from public.candidate_reactions r where r.candidate_id=c.id), '[]'::jsonb),
         (select count(*)::int from public.trip_comments cm where cm.candidate_id=c.id),
         c.created_at
    from public.trip_candidates c
   where c.trip_id=(select id from trip)
   order by c.created_at desc, c.id desc
$$;

-- ── 활동 기록 RPC ───────────────────────────────────────────────────────────

-- 최근 활동. 이름표는 읽는 시점에 만든다 — 나간 사람도 trip_members 행은 남아 있어 이름이 나온다.
-- 클라이언트가 문장을 만들 재료만 준다(§39 — 내부 구조를 그대로 노출하지 않는다는 뜻은 '문장'을 여기서 굳히지 않는 것이다).
create or replace function public.list_trip_activity(p_client_id text, p_limit int default 40)
returns table(id bigint, kind text, actor_label text, mine boolean, member_label text, subject jsonb, created_at timestamptz)
language sql stable security invoker set search_path=public as $$
  with trip as (
    select t.id from public.trips t
     where t.client_id=p_client_id and t.deleted_at is null and public.tc_trip_role(t.id) is not null
     order by (t.user_id=auth.uid()) desc, t.id limit 1
  )
  select a.id, a.kind,
         coalesce(public.tc_member_label(a.trip_id, a.actor_id), '멤버'),
         a.actor_id=auth.uid(),
         case when a.subject ? 'member_id'
              then coalesce(public.tc_member_label(a.trip_id, (a.subject->>'member_id')::uuid), '멤버') end,
         a.subject, a.created_at
    from public.trip_activity a
   where a.trip_id=(select id from trip)
   order by a.id desc
   limit greatest(1, least(coalesce(p_limit,40), 200))
$$;

-- ── 실시간 전달 ─────────────────────────────────────────────────────────────
-- trip_activity의 INSERT만 내보낸다. 클라이언트는 payload를 믿지 않고 RPC로 다시 읽는다(§41).
-- 구독자에게도 RLS(trip_activity_member_select)가 적용된다 — 멤버가 아닌 여행의 이벤트는 오지 않는다.

do $$ begin
  if not exists (select 1 from pg_publication where pubname='supabase_realtime') then
    create publication supabase_realtime;
  end if;
  if not exists (select 1 from pg_publication_tables
                  where pubname='supabase_realtime' and schemaname='public' and tablename='trip_activity') then
    alter publication supabase_realtime add table public.trip_activity;
  end if;
end $$;

-- ── 권한 ────────────────────────────────────────────────────────────────────
-- security definer 함수는 기본 public 실행 권한을 반드시 거둔다. 트리거 전용 함수는 authenticated에게도 주지 않는다.

do $$ declare t text; begin
  select format_type(a.atttypid, a.atttypmod) into t
    from pg_attribute a where a.attrelid='public.trips'::regclass and a.attname='id';
  execute format('revoke all on function public.tc_log_activity(%s, text, jsonb) from public, anon, authenticated', t);
end $$;
revoke all on function public.add_candidate_comment(bigint,text) from public,anon;
revoke all on function public.delete_candidate_comment(bigint) from public,anon;
revoke all on function public.list_candidate_comments(bigint) from public,anon;
revoke all on function public.list_trip_candidates(text) from public,anon;
revoke all on function public.list_trip_activity(text,int) from public,anon;

grant execute on function public.add_candidate_comment(bigint,text) to authenticated;
grant execute on function public.delete_candidate_comment(bigint) to authenticated;
grant execute on function public.list_candidate_comments(bigint) to authenticated;
grant execute on function public.list_trip_candidates(text) to authenticated;
grant execute on function public.list_trip_activity(text,int) to authenticated;
