-- 함께하기 2단계 — 후보 장소(TripCandidate)와 반응(MUST/OK/PASS).
--
-- 왜 여행 문서(jsonb) 안이 아니라 별도 테이블인가:
--  1. 반응은 **동시에** 들어온다. 넷이 같은 순간에 하트를 누르면 문서 리비전 CAS가 서로를 걷어찬다.
--  2. 보기 권한(VIEWER)도 의견은 낼 수 있어야 한다 — 문서 쓰기는 EDITOR 이상만 된다.
--  3. 한 사람 한 표를 DB가 보장해야 한다(unique). 문서 병합으로는 못 지킨다.
-- 확정 일정(Spot)은 지금처럼 여행 문서에 남는다. 후보는 **아직 일정이 아닌 것**이라 분리돼 있다.
--
-- 접근 경계는 여기(RLS)다. 읽기는 그 여행의 활성 멤버만, 쓰기 정책은 아예 없고 아래 RPC만 지난다.

-- ── 테이블 ──────────────────────────────────────────────────────────────────
-- trip_id는 trips.id와 같은 타입이어야 한다 — 실제 타입을 읽어 만든다(운영 uuid · 새 설치 bigint).

do $$ declare t text; begin
  select format_type(a.atttypid, a.atttypmod) into t
    from pg_attribute a where a.attrelid='public.trips'::regclass and a.attname='id';
  execute format($sql$
    create table if not exists public.trip_candidates (
      id bigint generated by default as identity primary key,
      trip_id %s not null references public.trips(id) on delete cascade,
      title text not null check (btrim(title) <> ''),
      -- 지도에서 담았으면 신원이 있고, 손으로 적었으면 없다. 없다고 후보가 못 되는 것은 아니다.
      place_id text, lat double precision, lng double precision, addr text,
      -- 왜 가고 싶은지 한 줄. 토론(코멘트)은 다음 단계다 — 여기는 제안자의 메모 한 줄뿐.
      note text, url text,
      proposed_by uuid not null references auth.users(id) on delete cascade,
      -- ACCEPTED는 아직 쓰지 않는다(합의 판정은 다음 단계) — 나중에 마이그레이션 없이 쓰려고 열어 둔다.
      status text not null default 'PROPOSED' check (status in ('PROPOSED','ACCEPTED','REJECTED','SCHEDULED')),
      -- 일정 어디에 넣었는지 — '2'(2일차) 같은 **위치 표시**다. 문서 안 장소에는 안정적인 id가 없다
      -- (normalizeTrip이 모르는 필드를 떨어뜨린다) → 장소를 가리키는 외래키를 만들 수 없다.
      scheduled_ref text,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    )$sql$, t);
end $$;

create table if not exists public.candidate_reactions (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.trip_candidates(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('MUST','OK','PASS')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- 한 사람 한 표. 다시 누르면 바뀐다(§66 — 같은 요청을 두 번 받아도 결과가 같다).
  unique (candidate_id, user_id)
);

create index if not exists trip_candidates_trip_idx on public.trip_candidates(trip_id, created_at desc);
create index if not exists candidate_reactions_cand_idx on public.candidate_reactions(candidate_id);

drop trigger if exists trip_candidates_touch on public.trip_candidates;
create trigger trip_candidates_touch before update on public.trip_candidates
  for each row execute function public.tc_touch_updated_at();
drop trigger if exists candidate_reactions_touch on public.candidate_reactions;
create trigger candidate_reactions_touch before update on public.candidate_reactions
  for each row execute function public.tc_touch_updated_at();

-- ── 헬퍼 ────────────────────────────────────────────────────────────────────

-- 후보가 속한 여행에 대한 내 역할. 정책 안에서 불리므로 security definer(재귀 없음).
create or replace function public.tc_candidate_role(p_candidate_id bigint)
returns text language sql stable security definer set search_path=public as $$
  select public.tc_trip_role(c.trip_id) from public.trip_candidates c where c.id=p_candidate_id
$$;
revoke all on function public.tc_candidate_role(bigint) from public, anon;
grant execute on function public.tc_candidate_role(bigint) to authenticated;

-- 이 여행에서 나를 뭐라고 부를까 — 계정 이메일은 절대 여행에 노출하지 않는다(§69).
-- 이름을 안 정했으면 역할로 부른다. 반환값은 화면에 그대로 나간다.
create or replace function public.tc_member_label(p_trip_id public.trips.id%type, p_user_id uuid)
returns text language sql stable security definer set search_path=public as $$
  select coalesce(
    nullif(btrim(coalesce(m.display_name,'')),''),
    case when m.role='OWNER' then '주최자' else '멤버' end,
    '멤버')
    from public.trip_members m
   where m.trip_id=p_trip_id and m.user_id=p_user_id
   limit 1
$$;
do $$ declare t text; begin
  select format_type(a.atttypid, a.atttypmod) into t
    from pg_attribute a where a.attrelid='public.trips'::regclass and a.attname='id';
  execute format('revoke all on function public.tc_member_label(%s, uuid) from public, anon', t);
  execute format('grant execute on function public.tc_member_label(%s, uuid) to authenticated', t);
end $$;

-- ── RLS ─────────────────────────────────────────────────────────────────────
-- 읽기만 정책으로 연다. 쓰기 정책은 만들지 않는다 — 전부 아래 RPC(security definer)를 지난다.

alter table public.trip_candidates enable row level security;
alter table public.candidate_reactions enable row level security;

drop policy if exists "trip_candidates_member_select" on public.trip_candidates;
create policy "trip_candidates_member_select" on public.trip_candidates for select to authenticated
  using (public.tc_trip_role(trip_id) is not null);

drop policy if exists "candidate_reactions_member_select" on public.candidate_reactions;
create policy "candidate_reactions_member_select" on public.candidate_reactions for select to authenticated
  using (public.tc_candidate_role(candidate_id) is not null);

-- Supabase는 새 테이블에 authenticated로 ALL을 기본 부여한다. 명시적으로 거두고 select만 준다.
revoke all on public.trip_candidates, public.candidate_reactions from anon, authenticated, public;
grant select on public.trip_candidates, public.candidate_reactions to authenticated;

-- ── 후보 RPC ────────────────────────────────────────────────────────────────

-- 후보 추가는 편집 권한(OWNER·EDITOR)이 있어야 한다.
-- 보기 권한은 **의견만** 낸다 — 여행에 내용을 만들지는 않는다(반응은 아래 react_to_candidate).
create or replace function public.add_trip_candidate(
  p_client_id text, p_title text, p_place_id text default null,
  p_lat double precision default null, p_lng double precision default null,
  p_addr text default null, p_note text default null, p_url text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_trip_id public.trips.id%type; v_role text; v_title text; v_id bigint;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  v_title := nullif(left(btrim(coalesce(p_title,'')), 120), '');
  if v_title is null then raise exception 'TITLE_REQUIRED' using errcode='22023', hint='후보에는 이름이 있어야 한다'; end if;
  select t.id into v_trip_id from public.trips t
   where t.client_id=p_client_id and t.deleted_at is null and public.tc_trip_role(t.id) is not null
   order by (t.user_id=v_uid) desc, t.id limit 1;
  if v_trip_id is null then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='이 여행을 볼 권한이 없다';
  end if;
  v_role := public.tc_trip_role(v_trip_id);
  if v_role is distinct from 'OWNER' and v_role is distinct from 'EDITOR' then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='보기 권한으로는 후보를 추가할 수 없다';
  end if;
  insert into public.trip_candidates(trip_id, title, place_id, lat, lng, addr, note, url, proposed_by)
  values (v_trip_id, v_title, nullif(btrim(coalesce(p_place_id,'')),''), p_lat, p_lng,
          nullif(left(btrim(coalesce(p_addr,'')),200),''), nullif(left(btrim(coalesce(p_note,'')),300),''),
          nullif(left(btrim(coalesce(p_url,'')),500),''), v_uid)
  returning id into v_id;
  -- 제안한 사람은 이미 가고 싶다는 뜻이다 — 한 번 더 누르게 하지 않는다.
  insert into public.candidate_reactions(candidate_id, user_id, reaction) values (v_id, v_uid, 'MUST')
    on conflict (candidate_id, user_id) do nothing;
  return v_id;
end $$;

-- 한 여행의 후보 전부 + 반응 집계 + 내 반응 + 누가 남겼는지.
-- 반응은 서로 볼 수 있다(§10 — 이번 단계는 공개 의견이 기본). 이름은 이 여행에서 쓰는 이름뿐이다.
create or replace function public.list_trip_candidates(p_client_id text)
returns table(id bigint, title text, place_id text, lat double precision, lng double precision,
              addr text, note text, url text, status text, scheduled_ref text,
              proposed_by_label text, mine boolean, my_reaction text,
              must_count int, ok_count int, pass_count int, reactions jsonb, created_at timestamptz)
language sql stable security invoker set search_path=public as $$
  with trip as (
    select t.id from public.trips t
     where t.client_id=p_client_id and t.deleted_at is null and public.tc_trip_role(t.id) is not null
     order by (t.user_id=auth.uid()) desc, t.id limit 1
  )
  select c.id, c.title, c.place_id, c.lat, c.lng, c.addr, c.note, c.url, c.status, c.scheduled_ref,
         public.tc_member_label(c.trip_id, c.proposed_by), c.proposed_by=auth.uid(),
         (select r.reaction from public.candidate_reactions r where r.candidate_id=c.id and r.user_id=auth.uid()),
         (select count(*)::int from public.candidate_reactions r where r.candidate_id=c.id and r.reaction='MUST'),
         (select count(*)::int from public.candidate_reactions r where r.candidate_id=c.id and r.reaction='OK'),
         (select count(*)::int from public.candidate_reactions r where r.candidate_id=c.id and r.reaction='PASS'),
         coalesce((select jsonb_agg(jsonb_build_object(
                     'name', public.tc_member_label(c.trip_id, r.user_id),
                     'reaction', r.reaction,
                     'me', r.user_id=auth.uid()) order by r.created_at, r.id)
                     from public.candidate_reactions r where r.candidate_id=c.id), '[]'::jsonb),
         c.created_at
    from public.trip_candidates c
   where c.trip_id=(select id from trip)
   order by c.created_at desc, c.id desc
$$;

-- 반응 — 활성 멤버라면 **보기 권한도** 할 수 있다. 의견을 내는 것은 일정을 바꾸는 것이 아니다.
-- 같은 반응을 두 번 눌러도 결과가 같고(멱등), null을 주면 반응을 거둔다.
create or replace function public.react_to_candidate(p_candidate_id bigint, p_reaction text default null)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_role text; v_reaction text;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  v_role := public.tc_candidate_role(p_candidate_id);
  if v_role is null then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='이 여행의 멤버가 아니다';
  end if;
  v_reaction := nullif(btrim(upper(coalesce(p_reaction,''))), '');
  if v_reaction is null then
    delete from public.candidate_reactions r where r.candidate_id=p_candidate_id and r.user_id=v_uid;
    return true;
  end if;
  if v_reaction not in ('MUST','OK','PASS') then
    raise exception 'INVALID_REACTION' using errcode='22023', hint='반응은 MUST · OK · PASS';
  end if;
  insert into public.candidate_reactions(candidate_id, user_id, reaction)
  values (p_candidate_id, v_uid, v_reaction)
  on conflict (candidate_id, user_id) do update set reaction=excluded.reaction, updated_at=now();
  return true;
end $$;

-- REMOVE는 제안한 사람이나 주최자만(내가 낸 의견은 내가 거둔다).
-- SCHEDULE·UNSCHEDULE은 편집 권한 — 일정에 실제로 넣는 것은 여행 문서를 바꾸는 일이다.
-- 인기가 많다고 자동으로 일정에 들어가지 않는다(§12·§79) — 넣는 것은 언제나 사람이 누른다.
create or replace function public.manage_trip_candidate(p_candidate_id bigint, p_action text, p_value text default null)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_uid uuid := auth.uid(); v_cand public.trip_candidates%rowtype; v_role text; v_owner uuid;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  select c.* into v_cand from public.trip_candidates c where c.id=p_candidate_id for update;
  if not found then return false; end if;
  v_role := public.tc_trip_role(v_cand.trip_id);
  if v_role is null then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='이 여행의 멤버가 아니다';
  end if;
  select t.user_id into v_owner from public.trips t where t.id=v_cand.trip_id;
  if p_action='REMOVE' then
    if v_uid<>v_cand.proposed_by and v_uid<>v_owner then
      raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='후보는 제안한 사람이나 주최자만 지운다';
    end if;
    delete from public.trip_candidates c where c.id=v_cand.id;
    return true;
  end if;
  if v_role is distinct from 'OWNER' and v_role is distinct from 'EDITOR' then
    raise exception 'TRIP_FORBIDDEN' using errcode='42501', hint='보기 권한으로는 후보 상태를 바꿀 수 없다';
  end if;
  if p_action='SCHEDULE' then
    update public.trip_candidates c set status='SCHEDULED', scheduled_ref=nullif(btrim(coalesce(p_value,'')),'')
     where c.id=v_cand.id;
    return true;
  elsif p_action='UNSCHEDULE' then
    update public.trip_candidates c set status='PROPOSED', scheduled_ref=null where c.id=v_cand.id;
    return true;
  end if;
  raise exception 'INVALID_ACTION' using errcode='22023', hint='REMOVE · SCHEDULE · UNSCHEDULE';
end $$;

-- ── 권한 ────────────────────────────────────────────────────────────────────
-- security definer 함수는 기본 public 실행 권한을 반드시 거둔다.

revoke all on function public.add_trip_candidate(text,text,text,double precision,double precision,text,text,text) from public,anon;
revoke all on function public.list_trip_candidates(text) from public,anon;
revoke all on function public.react_to_candidate(bigint,text) from public,anon;
revoke all on function public.manage_trip_candidate(bigint,text,text) from public,anon;

grant execute on function public.add_trip_candidate(text,text,text,double precision,double precision,text,text,text) to authenticated;
grant execute on function public.list_trip_candidates(text) to authenticated;
grant execute on function public.react_to_candidate(bigint,text) to authenticated;
grant execute on function public.manage_trip_candidate(bigint,text,text) to authenticated;
